%%0. import util functions
addpath('utils')
addpath('utils/m_map')
%%
%%1. read the wavefront surfaces generated by ImageJ and extract the shape signatures
for i = 0:1:17
    disp(['Stage: ', num2str(i)])
    obj = readObj(['signature/surfaceData/',num2str(i,'%03d'),'.tif.obj']);
    centroid = mean(obj.v);
    obj.v = obj.v-centroid;
    obj.v = particleRot(obj.v,-12.5,10,0); %-12.5
    % scatter3(obj.v(:,1),obj.v(:,2),obj.v(:,3))
    % axis equal
    sig = signature_extractor(obj,[0,0,0]);
    save(['signature/sigData/',num2str(i,'%03d'),'.mat'],'sig')
end
%%
%%%2. draw the shape signature projections
sigStack = zeros([91,181,18]);
for i = 0:1:17
    sigStack(:,:,i+1) = load(['signature/sigData/',num2str(i,'%03d'),'.mat']).sig;
    figure(1);clf(1);
    set(gcf,'position',[200 200 512 512])
    set(gca,'position',[0 0 1 1])
    dec=-90:2:90;
    ra=(180:-2:-180);
    m_proj('stereographic','lat',0,'long',0,'radius',90);
    obj=m_pcolor(ra,dec,sigStack(:,:,i+1)); 
    shading interp; 
    mymap=colormap('hot');
    colormap(mymap);
    clim([0 60]);
    axis off
    drawnow
    saveas(gcf,['signature/sigVisualize/' ,num2str(i,'%03d') , '.png'])
end

figure(2);clf
box off 
axis off
h = colorbar();
colormap(mymap)
clim([0 60])
set(gcf,'color','w');
ylabel(h,'d(theta, phi) (nm)');
saveas(gcf,['signature/sigVisualize/colorbar.png'])
%%
%%%3. measure the etching rates
stepSize = 5;
rateStack = (sigStack(:,:,1:end-stepSize)-sigStack(:,:,stepSize+1:end))/stepSize/75.8; %75.8 s is the average time interval between two nearby stages
for i = 1:1:(17-stepSize+1)
    figure(1);clf(1);
    set(gcf,'position',[200 200 512 512])
    set(gca,'position',[0 0 1 1])
    dec=-90:2:90;
    ra=(180:-2:-180);
    m_proj('stereographic','lat',0,'long',0,'radius',90);
    obj=m_pcolor(ra,dec,rateStack(:,:,i)); 
    shading interp; 
    mymap=colormap('hot');
    colormap(mymap);
    clim([0 0.04]);
    axis off
    drawnow
    saveas(gcf,['signature/rateVisualize/' ,num2str(i,'%03d') , '.png'])
end

figure(2);clf
box off 
axis off
h = colorbar();
colormap(mymap)
clim([0 0.04]);
set(gcf,'color','w');
ylabel(h,'d(theta, phi) (nm)');
saveas(gcf,['signature/rateVisualize/colorbar.png'])
%%
%%%4. measure the average etching rate at all times
figure(1);clf(1);
    set(gcf,'position',[200 200 512 512])
    set(gca,'position',[0 0 1 1])
    set(gcf,'color','w');
    m_proj('stereographic','lat',0,'long',0,'radius',90);
    obj=m_pcolor(ra,dec,mean(rateStack,3)); 
    shading interp; 
    mymap=colormap('hot');
    colormap(mymap);
    axis off
    clim([0 0.04]);
    drawnow
saveas(gcf,['signature/rateVisualize/all.png'])
%%
%%% functions
function v = particleRot(v,xy1,y,xy2)
    Rxy1 = [cosd(xy1) -sind(xy1) 0;
          sind(xy1)  cosd(xy1) 0;
          0 0 1];  
    v = v*Rxy1;  
    
    Ry = [1           0            0;
          0 cosd(y) -sind(y);
          0 sind(y)  cosd(y)];
    v = v*Ry;  
    
    Rxy2 = [cosd(xy2) -sind(xy2) 0;
          sind(xy2)  cosd(xy2) 0;
          0 0 1];  
    v = v*Rxy2;
end